/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-common-monitoring2.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-common-monitoring2.yang */
public class tailfCommonMonitoring2 extends ConfNamespace {
    public static final int hash = 2025864089;
    public int hash() {
        return tailfCommonMonitoring2.hash;
    }

    public static final String id = "_cisco-nso-nc-6.1:cisco-nso-nc-6.1#http://tail-f.com/yang/common-monitoring2";
    public String id() {
        return tailfCommonMonitoring2.id;
    }

    public static final String uri = "_cisco-nso-nc-6.1:cisco-nso-nc-6.1#http://tail-f.com/yang/common-monitoring2";
    public String uri() {
        return tailfCommonMonitoring2.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfCommonMonitoring2.uri);
    }

    public static final String prefix = "tfcg2";
    public String prefix() {
        return tailfCommonMonitoring2.prefix;
    }

    public tailfCommonMonitoring2() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
