/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-cisco-nso-nc-6.1.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-cisco-nso-nc-6.1.yang */
public class tailfNedIdCiscoNsoNc6_1 extends ConfNamespace {
    public static final int hash = 1369142666;
    public int hash() {
        return tailfNedIdCiscoNsoNc6_1.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/cisco-nso-nc-6.1";
    public String id() {
        return tailfNedIdCiscoNsoNc6_1.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/cisco-nso-nc-6.1";
    public String uri() {
        return tailfNedIdCiscoNsoNc6_1.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdCiscoNsoNc6_1.uri);
    }

    public static final String prefix = "cisco-nso-nc-6.1";
    public String prefix() {
        return tailfNedIdCiscoNsoNc6_1.prefix;
    }

    public tailfNedIdCiscoNsoNc6_1() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_nso_nc_60x2e1 = 525197788;
    public static final String _cisco_nso_nc_60x2e1_ = "cisco-nso-nc-6.1";
}
