#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-cisco-nso-nc-6.0.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-cisco-nso-nc-6.0.yang


class ns(object):
    hash = 148977973

    id = "http://tail-f.com/ns/ned-id/cisco-nso-nc-6.0"

    uri = "http://tail-f.com/ns/ned-id/cisco-nso-nc-6.0"

    prefix = "cisco-nso-nc-6.0"

    cisco_nso_nc_60x2e0_cisco_nso_nc_60x2e0 = 1431833348
    cisco_nso_nc_60x2e0_cisco_nso_nc_60x2e0_ = "cisco-nso-nc-6.0"
