#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-common-monitoring2.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-common-monitoring2.yang


class ns(object):
    hash = 676049898

    id = "_cisco-nso-nc-6.0:cisco-nso-nc-6.0#http://tail-f.com/yang/common-monitoring2"

    uri = "_cisco-nso-nc-6.0:cisco-nso-nc-6.0#http://tail-f.com/yang/common-monitoring2"

    prefix = "tfcg2"

    tfcg2_PENDING = 0
    tfcg2_PENDING_ = "PENDING"
    tfcg2_pending_subscription = 3
    tfcg2_pending_subscription_ = "pending-subscription"
    tfcg2_inactive = 0
    tfcg2_inactive_ = "inactive"
    tfcg2_phase1 = 2
    tfcg2_phase1_ = "phase1"
    tfcg2_subscriber = 2
    tfcg2_subscriber_ = "subscriber"
    tfcg2_NOT_REGISTERED = 0
    tfcg2_NOT_REGISTERED_ = "NOT-REGISTERED"
    tfcg2_external = 2
    tfcg2_external_ = "external"
    tfcg2_relay_secondary = 3
    tfcg2_relay_secondary_ = "relay-secondary"
    tfcg2_secondary = 1
    tfcg2_secondary_ = "secondary"
    tfcg2_stopping = 4
    tfcg2_stopping_ = "stopping"
    tfcg2_primary = 2
    tfcg2_primary_ = "primary"
    tfcg2_client = 1
    tfcg2_client_ = "client"
    tfcg2_started = 3
    tfcg2_started_ = "started"
    tfcg2_starting = 0
    tfcg2_starting_ = "starting"
    tfcg2_UNKNOWN = 1
    tfcg2_UNKNOWN_ = "UNKNOWN"
    tfcg2_pending_read = 2
    tfcg2_pending_read_ = "pending-read"
    tfcg2_phase0 = 1
    tfcg2_phase0_ = "phase0"
    tfcg2_none = 0
    tfcg2_none_ = "none"
    tfcg2_waiting = 3
    tfcg2_waiting_ = "waiting"
    tfcg2_read = 0
    tfcg2_read_ = "read"
    tfcg2_subscription = 1
    tfcg2_subscription_ = "subscription"
    tfcg2_builtin = 1
    tfcg2_builtin_ = "builtin"
