/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ncs-high-availability-raft.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ncs-high-availability-raft.yang */
public class tailfNcsHighAvailabilityRaft extends ConfNamespace {
    public static final int hash = 277340114;
    public int hash() {
        return tailfNcsHighAvailabilityRaft.hash;
    }

    public static final String id = "_cisco-nso-nc-6.2:cisco-nso-nc-6.2#http://tail-f.com/ns/ncs/high-availability/raft";
    public String id() {
        return tailfNcsHighAvailabilityRaft.id;
    }

    public static final String uri = "_cisco-nso-nc-6.2:cisco-nso-nc-6.2#http://tail-f.com/ns/ncs/high-availability/raft";
    public String uri() {
        return tailfNcsHighAvailabilityRaft.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNcsHighAvailabilityRaft.uri);
    }

    public static final String prefix = "haraft";
    public String prefix() {
        return tailfNcsHighAvailabilityRaft.prefix;
    }

    public tailfNcsHighAvailabilityRaft() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _file_path = 1030840950;
    public static final String _file_path_ = "file-path";
    public static final int    _applied_index = 320088978;
    public static final String _applied_index_ = "applied-index";
    public static final int    _mode = 575893728;
    public static final String _mode_ = "mode";
    public static final int    _leader = 1629073517;
    public static final String _leader_ = "leader";
    public static final int    _replications = 1523060205;
    public static final String _replications_ = "replications";
    public static final int    _force = 1475309827;
    public static final String _force_ = "force";
    public static final int    _serial_number = 544353266;
    public static final String _serial_number_ = "serial-number";
    public static final int    _lag = 2057913915;
    public static final String _lag_ = "lag";
    public static final int    _certificate = 929395308;
    public static final String _certificate_ = "certificate";
    public static final int    _to_member = 1229652994;
    public static final String _to_member_ = "to-member";
    public static final int    _log = 1285913844;
    public static final String _log_ = "log";
    public static final int    _local_node = 1170793894;
    public static final String _local_node_ = "local-node";
    public static final int    _command = 36215204;
    public static final String _command_ = "command";
    public static final int    _num_entries = 710914878;
    public static final String _num_entries_ = "num-entries";
    public static final int    _ha_raft = 994001503;
    public static final String _ha_raft_ = "ha-raft";
    public static final int    _read_only = 1971071769;
    public static final String _read_only_ = "read-only";
    public static final int    _role = 1297556411;
    public static final String _role_ = "role";
    public static final int    _certificates = 2105107206;
    public static final String _certificates_ = "certificates";
    public static final int    _handover = 498069291;
    public static final String _handover_ = "handover";
    public static final int    _disable_reason = 1746174423;
    public static final String _disable_reason_ = "disable-reason";
    public static final int    _reset = 888276656;
    public static final String _reset_ = "reset";
    public static final int    _remove_node = 1796466923;
    public static final String _remove_node_ = "remove-node";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _create_cluster = 142627614;
    public static final String _create_cluster_ = "create-cluster";
    public static final int    _status = 1950810920;
    public static final String _status_ = "status";
    public static final int    _certificate_authority = 1018824378;
    public static final String _certificate_authority_ = "certificate-authority";
    public static final int    _index = 827593980;
    public static final String _index_ = "index";
    public static final int    _connected_node = 975244607;
    public static final String _connected_node_ = "connected-node";
    public static final int    _member = 387693123;
    public static final String _member_ = "member";
    public static final int    _expiration_date = 1696100980;
    public static final String _expiration_date_ = "expiration-date";
    public static final int    _node = 2084421367;
    public static final String _node_ = "node";
    public static final int    _current_index = 1709389408;
    public static final String _current_index_ = "current-index";
    public static final int    _disconnect = 805481644;
    public static final String _disconnect_ = "disconnect";
    public static final int    _adjust_membership = 279131311;
    public static final String _adjust_membership_ = "adjust-membership";
    public static final int    _add_node = 221508568;
    public static final String _add_node_ = "add-node";
}
