/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ncs-devices-cisco-smart-license.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ncs-devices-cisco-smart-license.yang */
public class tailfNcsDevicesCiscoSmartLicense extends ConfNamespace {
    public static final int hash = 1760095787;
    public int hash() {
        return tailfNcsDevicesCiscoSmartLicense.hash;
    }

    public static final String id = "_cisco-nso-nc-6.2:cisco-nso-nc-6.2#http://tail-f.com/ns/ncs/devices/cisco-smart-license";
    public String id() {
        return tailfNcsDevicesCiscoSmartLicense.id;
    }

    public static final String uri = "_cisco-nso-nc-6.2:cisco-nso-nc-6.2#http://tail-f.com/ns/ncs/devices/cisco-smart-license";
    public String uri() {
        return tailfNcsDevicesCiscoSmartLicense.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNcsDevicesCiscoSmartLicense.uri);
    }

    public static final String prefix = "devices-cisco-smart-license";
    public String prefix() {
        return tailfNcsDevicesCiscoSmartLicense.prefix;
    }

    public tailfNcsDevicesCiscoSmartLicense() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _virtual_account = 142616774;
    public static final String _virtual_account_ = "virtual-account";
    public static final int    _registration = 1291428179;
    public static final String _registration_ = "registration";
    public static final int    _smart_license = 1738214871;
    public static final String _smart_license_ = "smart-license";
    public static final int    _utility = 738029406;
    public static final String _utility_ = "utility";
    public static final int    _smart_account = 1071198990;
    public static final String _smart_account_ = "smart-account";
    public static final int    _transport = 514190987;
    public static final String _transport_ = "transport";
    public static final int    _authorization_state = 931372143;
    public static final String _authorization_state_ = "authorization-state";
    public static final int    _transport_type = 138862728;
    public static final String _transport_type_ = "transport-type";
    public static final int    _registration_state = 1587905256;
    public static final String _registration_state_ = "registration-state";
    public static final int    _authorization = 1275762932;
    public static final String _authorization_ = "authorization";
}
