#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-cisco-nso-nc-6.1.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-cisco-nso-nc-6.1.yang


class ns(object):
    hash = 1369142666

    id = "http://tail-f.com/ns/ned-id/cisco-nso-nc-6.1"

    uri = "http://tail-f.com/ns/ned-id/cisco-nso-nc-6.1"

    prefix = "cisco-nso-nc-6.1"

    cisco_nso_nc_60x2e1_cisco_nso_nc_60x2e1 = 525197788
    cisco_nso_nc_60x2e1_cisco_nso_nc_60x2e1_ = "cisco-nso-nc-6.1"
