#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-cisco-nso-nc-6.2.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-cisco-nso-nc-6.2.yang


class ns(object):
    hash = 1957354366

    id = "http://tail-f.com/ns/ned-id/cisco-nso-nc-6.2"

    uri = "http://tail-f.com/ns/ned-id/cisco-nso-nc-6.2"

    prefix = "cisco-nso-nc-6.2"

    cisco_nso_nc_60x2e2_cisco_nso_nc_60x2e2 = 1361096212
    cisco_nso_nc_60x2e2_cisco_nso_nc_60x2e2_ = "cisco-nso-nc-6.2"
