#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ncs-devices-cisco-smart-license.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ncs-devices-cisco-smart-license.yang


class ns(object):
    hash = 1760095787

    id = "_cisco-nso-nc-6.2:cisco-nso-nc-6.2#http://tail-f.com/ns/ncs/devices/cisco-smart-license"

    uri = "_cisco-nso-nc-6.2:cisco-nso-nc-6.2#http://tail-f.com/ns/ncs/devices/cisco-smart-license"

    prefix = "devices-cisco-smart-license"

    devices_cisco_smart_license_enabled = 197426095
    devices_cisco_smart_license_enabled_ = "enabled"
    devices_cisco_smart_license_reg_state_complete = 1
    devices_cisco_smart_license_reg_state_complete_ = "reg-state-complete"
    devices_cisco_smart_license_virtual_account = 142616774
    devices_cisco_smart_license_virtual_account_ = "virtual-account"
    devices_cisco_smart_license_transport_type_smart = 1
    devices_cisco_smart_license_transport_type_smart_ = "transport-type-smart"
    devices_cisco_smart_license_registration = 1291428179
    devices_cisco_smart_license_registration_ = "registration"
    devices_cisco_smart_license_auth_state_out_of_compliance = 5
    devices_cisco_smart_license_auth_state_out_of_compliance_ = "auth-state-out-of-compliance"
    devices_cisco_smart_license_smart_license = 1738214871
    devices_cisco_smart_license_smart_license_ = "smart-license"
    devices_cisco_smart_license_utility = 738029406
    devices_cisco_smart_license_utility_ = "utility"
    devices_cisco_smart_license_smart_account = 1071198990
    devices_cisco_smart_license_smart_account_ = "smart-account"
    devices_cisco_smart_license_reg_state_in_progress = 2
    devices_cisco_smart_license_reg_state_in_progress_ = "reg-state-in-progress"
    devices_cisco_smart_license_auth_state_eval = 1
    devices_cisco_smart_license_auth_state_eval_ = "auth-state-eval"
    devices_cisco_smart_license_auth_state_authorized = 3
    devices_cisco_smart_license_auth_state_authorized_ = "auth-state-authorized"
    devices_cisco_smart_license_transport = 514190987
    devices_cisco_smart_license_transport_ = "transport"
    devices_cisco_smart_license_auth_state_authorized_reservation = 4
    devices_cisco_smart_license_auth_state_authorized_reservation_ = "auth-state-authorized-reservation"
    devices_cisco_smart_license_transport_type_callhome = 0
    devices_cisco_smart_license_transport_type_callhome_ = "transport-type-callhome"
    devices_cisco_smart_license_auth_state_eval_expired = 2
    devices_cisco_smart_license_auth_state_eval_expired_ = "auth-state-eval-expired"
    devices_cisco_smart_license_authorization_state = 931372143
    devices_cisco_smart_license_authorization_state_ = "authorization-state"
    devices_cisco_smart_license_reg_state_not_registered = 0
    devices_cisco_smart_license_reg_state_not_registered_ = "reg-state-not-registered"
    devices_cisco_smart_license_reg_state_failed = 4
    devices_cisco_smart_license_reg_state_failed_ = "reg-state-failed"
    devices_cisco_smart_license_transport_type = 138862728
    devices_cisco_smart_license_transport_type_ = "transport-type"
    devices_cisco_smart_license_auth_state_none = 0
    devices_cisco_smart_license_auth_state_none_ = "auth-state-none"
    devices_cisco_smart_license_auth_state_authorization_expired = 6
    devices_cisco_smart_license_auth_state_authorization_expired_ = "auth-state-authorization-expired"
    devices_cisco_smart_license_reg_state_retry = 3
    devices_cisco_smart_license_reg_state_retry_ = "reg-state-retry"
    devices_cisco_smart_license_registration_state = 1587905256
    devices_cisco_smart_license_registration_state_ = "registration-state"
    devices_cisco_smart_license_authorization = 1275762932
    devices_cisco_smart_license_authorization_ = "authorization"
