#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ncs-high-availability-raft.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ncs-high-availability-raft.yang


class ns(object):
    hash = 277340114

    id = "_cisco-nso-nc-6.2:cisco-nso-nc-6.2#http://tail-f.com/ns/ncs/high-availability/raft"

    uri = "_cisco-nso-nc-6.2:cisco-nso-nc-6.2#http://tail-f.com/ns/ncs/high-availability/raft"

    prefix = "haraft"

    haraft_file_path = 1030840950
    haraft_file_path_ = "file-path"
    haraft_applied_index = 320088978
    haraft_applied_index_ = "applied-index"
    haraft_ha_raft_log_catchup = 2
    haraft_ha_raft_log_catchup_ = "requires-catchup"
    haraft_mode = 575893728
    haraft_mode_ = "mode"
    haraft_leader = 1629073517
    haraft_leader_ = "leader"
    haraft_ha_raft_log_snapshot = 3
    haraft_ha_raft_log_snapshot_ = "requires-snapshot"
    haraft_replications = 1523060205
    haraft_replications_ = "replications"
    haraft_ha_raft_follower = 2
    haraft_ha_raft_follower_ = "follower"
    haraft_force = 1475309827
    haraft_force_ = "force"
    haraft_serial_number = 544353266
    haraft_serial_number_ = "serial-number"
    haraft_lag = 2057913915
    haraft_lag_ = "lag"
    haraft_certificate = 929395308
    haraft_certificate_ = "certificate"
    haraft_to_member = 1229652994
    haraft_to_member_ = "to-member"
    haraft_log = 1285913844
    haraft_log_ = "log"
    haraft_local_node = 1170793894
    haraft_local_node_ = "local-node"
    haraft_command = 36215204
    haraft_command_ = "command"
    haraft_ha_raft_log_process = 1
    haraft_ha_raft_log_process_ = "in-process"
    haraft_num_entries = 710914878
    haraft_num_entries_ = "num-entries"
    haraft_ha_raft = 994001503
    haraft_ha_raft_ = "ha-raft"
    haraft_read_only = 1971071769
    haraft_read_only_ = "read-only"
    haraft_role = 1297556411
    haraft_role_ = "role"
    haraft_certificates = 2105107206
    haraft_certificates_ = "certificates"
    haraft_ha_raft_candidate = 1
    haraft_ha_raft_candidate_ = "candidate"
    haraft_handover = 498069291
    haraft_handover_ = "handover"
    haraft_disable_reason = 1746174423
    haraft_disable_reason_ = "disable-reason"
    haraft_reset = 888276656
    haraft_reset_ = "reset"
    haraft_remove_node = 1796466923
    haraft_remove_node_ = "remove-node"
    haraft_state = 630973766
    haraft_state_ = "state"
    haraft_ha_raft_log_sync = 0
    haraft_ha_raft_log_sync_ = "in-sync"
    haraft_ha_raft_stalled = 0
    haraft_ha_raft_stalled_ = "stalled"
    haraft_create_cluster = 142627614
    haraft_create_cluster_ = "create-cluster"
    haraft_status = 1950810920
    haraft_status_ = "status"
    haraft_certificate_authority = 1018824378
    haraft_certificate_authority_ = "certificate-authority"
    haraft_index = 827593980
    haraft_index_ = "index"
    haraft_connected_node = 975244607
    haraft_connected_node_ = "connected-node"
    haraft_member = 387693123
    haraft_member_ = "member"
    haraft_ha_raft_leader = 3
    haraft_ha_raft_leader_ = "leader"
    haraft_expiration_date = 1696100980
    haraft_expiration_date_ = "expiration-date"
    haraft_node = 2084421367
    haraft_node_ = "node"
    haraft_current_index = 1709389408
    haraft_current_index_ = "current-index"
    haraft_ha_raft_disabled = 4
    haraft_ha_raft_disabled_ = "disabled"
    haraft_disconnect = 805481644
    haraft_disconnect_ = "disconnect"
    haraft_adjust_membership = 279131311
    haraft_adjust_membership_ = "adjust-membership"
    haraft_add_node = 221508568
    haraft_add_node_ = "add-node"
