#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-progress.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-progress.yang


class ns(object):
    hash = 655149032

    id = "_cisco-nso-nc-6.2:cisco-nso-nc-6.2#http://tail-f.com/ns/progress"

    uri = "_cisco-nso-nc-6.2:cisco-nso-nc-6.2#http://tail-f.com/ns/progress"

    prefix = "progress"

    progress_normal = 0
    progress_normal_ = "normal"
    progress_very_verbose = 2
    progress_very_verbose_ = "very-verbose"
    progress_enabled = 197426095
    progress_enabled_ = "enabled"
    progress_duration = 686902226
    progress_duration_ = "duration"
    progress_unlimited = 0
    progress_unlimited_ = "unlimited"
    progress_format = 1150348190
    progress_format_ = "format"
    progress_age_spec = 1564313084
    progress_age_spec_ = "age-spec"
    progress_oper_data = 454130417
    progress_oper_data_ = "oper-data"
    progress_datastore = 449538578
    progress_datastore_ = "datastore"
    progress_phase = 1431747117
    progress_phase_ = "phase"
    progress_netconf = 0
    progress_netconf_ = "netconf"
    progress_context = 1600175075
    progress_context_ = "context"
    progress_seconds = 1442107370
    progress_seconds_ = "seconds"
    progress_log = 1
    progress_log_ = "log"
    progress_csv = 0
    progress_csv_ = "csv"
    progress_file = 867066344
    progress_file_ = "file"
    progress_purge = 521476653
    progress_purge_ = "purge"
    progress_minutes = 1222309332
    progress_minutes_ = "minutes"
    progress_event = 1332659655
    progress_event_ = "event"
    progress_hours = 1625129637
    progress_hours_ = "hours"
    progress_link = 481374722
    progress_link_ = "link"
    progress_max_size = 1087447952
    progress_max_size_ = "max-size"
    progress_transaction_commit = 3
    progress_transaction_commit_ = "commit"
    progress_system = 5
    progress_system_ = "system"
    progress_name = 1998270519
    progress_name_ = "name"
    progress_verbose = 1
    progress_verbose_ = "verbose"
    progress_value = 864367181
    progress_value_ = "value"
    progress_snmp = 3
    progress_snmp_ = "snmp"
    progress_timestamp = 35058824
    progress_timestamp_ = "timestamp"
    progress_purged_events = 608871404
    progress_purged_events_ = "purged-events"
    progress_weeks = 323453812
    progress_weeks_ = "weeks"
    progress_rest = 4
    progress_rest_ = "rest"
    progress_message = 1674281495
    progress_message_ = "message"
    progress_transaction_validate = 0
    progress_transaction_validate_ = "validate"
    progress_parent_span_id = 1685057287
    progress_parent_span_id_ = "parent-span-id"
    progress_trace = 1896625767
    progress_trace_ = "trace"
    progress_days = 723976734
    progress_days_ = "days"
    progress_transaction_write_start = 1
    progress_transaction_write_start_ = "write-start"
    progress_debug = 3
    progress_debug_ = "debug"
    progress_older_than = 1805080387
    progress_older_than_ = "older-than"
    progress_transaction_abort = 4
    progress_transaction_abort_ = "abort"
    progress_span_id = 1528996286
    progress_span_id_ = "span-id"
    progress_webui = 2
    progress_webui_ = "webui"
    progress_progress = 1202957834
    progress_progress_ = "progress"
    progress_cli = 1
    progress_cli_ = "cli"
    progress_local_user = 1479564322
    progress_local_user_ = "local-user"
    progress_transaction_id = 1239501533
    progress_transaction_id_ = "transaction-id"
    progress_pre_commit_running = 1425038667
    progress_pre_commit_running_ = "pre-commit-running"
    progress_trace_id = 1065151221
    progress_trace_id_ = "trace-id"
    progress_filter = 518848087
    progress_filter_ = "filter"
    progress_timer = 337753833
    progress_timer_ = "timer"
    progress_subsystem = 1972091070
    progress_subsystem_ = "subsystem"
    progress_transaction_prepare = 2
    progress_transaction_prepare_ = "prepare"
    progress_destination = 1426812369
    progress_destination_ = "destination"
    progress_attribute = 926410606
    progress_attribute_ = "attribute"
    progress_session_id = 372565948
    progress_session_id_ = "session-id"
    progress_verbosity = 680524267
    progress_verbosity_ = "verbosity"
    progress_annotation = 87780038
    progress_annotation_ = "annotation"
