%%% This file was automatically generated by snmpc_mib_to_hrl
-ifndef('CISCO-SNMP-USM-OIDS-MIB').
-define('CISCO-SNMP-USM-OIDS-MIB', true).

%% Oids

-define(ciscoSnmpUsmOidsMIB, [1,3,6,1,4,1,9,12,6]).

-define(ciscoSnmpPrivProtocols, [1,3,6,1,4,1,9,12,6,1]).

-define(cusmAESCfb192PrivProtocol, [1,3,6,1,4,1,9,12,6,1,1]).

-define(cusmAESCfb256PrivProtocol, [1,3,6,1,4,1,9,12,6,1,2]).

-define(cusm3DES168PrivProtocol, [1,3,6,1,4,1,9,12,6,1,3]).


%% Range values


%% Default values

-endif.
