#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-cisco-nso-nc-5.8.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-cisco-nso-nc-5.8.yang


class ns(object):
    hash = 816864996

    id = "http://tail-f.com/ns/ned-id/cisco-nso-nc-5.8"

    uri = "http://tail-f.com/ns/ned-id/cisco-nso-nc-5.8"

    prefix = "cisco-nso-nc-5.8"

    cisco_nso_nc_50x2e8_cisco_nso_nc_50x2e8 = 1593089280
    cisco_nso_nc_50x2e8_cisco_nso_nc_50x2e8_ = "cisco-nso-nc-5.8"
