%%% This file was automatically generated by snmpc_mib_to_hrl
-ifndef('CISCO-SMI').
-define('CISCO-SMI', true).

%% Oids

-define(cisco, [1,3,6,1,4,1,9]).

-define(ciscoProducts, [1,3,6,1,4,1,9,1]).

-define(local, [1,3,6,1,4,1,9,2]).

-define(temporary, [1,3,6,1,4,1,9,3]).

-define(pakmon, [1,3,6,1,4,1,9,4]).

-define(workgroup, [1,3,6,1,4,1,9,5]).

-define(otherEnterprises, [1,3,6,1,4,1,9,6]).

-define(ciscoSB, [1,3,6,1,4,1,9,6,1]).

-define(ciscoSMB, [1,3,6,1,4,1,9,6,2]).

-define(ciscoAgentCapability, [1,3,6,1,4,1,9,7]).

-define(ciscoConfig, [1,3,6,1,4,1,9,8]).

-define(ciscoMgmt, [1,3,6,1,4,1,9,9]).

-define(ciscoExperiment, [1,3,6,1,4,1,9,10]).

-define(ciscoAdmin, [1,3,6,1,4,1,9,11]).

-define(ciscoProxy, [1,3,6,1,4,1,9,11,1]).

-define(ciscoPartyProxy, [1,3,6,1,4,1,9,11,1,1]).

-define(ciscoContextProxy, [1,3,6,1,4,1,9,11,1,2]).

-define(ciscoRptrGroupObjectID, [1,3,6,1,4,1,9,11,2]).

-define(ciscoUnknownRptrGroup, [1,3,6,1,4,1,9,11,2,1]).

-define(cisco2505RptrGroup, [1,3,6,1,4,1,9,11,2,2]).

-define(cisco2507RptrGroup, [1,3,6,1,4,1,9,11,2,3]).

-define(cisco2516RptrGroup, [1,3,6,1,4,1,9,11,2,4]).

-define(ciscoWsx5020RptrGroup, [1,3,6,1,4,1,9,11,2,5]).

-define(ciscoChipSets, [1,3,6,1,4,1,9,11,3]).

-define(ciscoChipSetSaint1, [1,3,6,1,4,1,9,11,3,1]).

-define(ciscoChipSetSaint2, [1,3,6,1,4,1,9,11,3,2]).

-define(ciscoChipSetSaint3, [1,3,6,1,4,1,9,11,3,3]).

-define(ciscoChipSetSaint4, [1,3,6,1,4,1,9,11,3,4]).

-define(ciscoModules, [1,3,6,1,4,1,9,12]).

-define(lightstream, [1,3,6,1,4,1,9,13]).

-define(ciscoworks, [1,3,6,1,4,1,9,14]).

-define(newport, [1,3,6,1,4,1,9,15]).

-define(ciscoPartnerProducts, [1,3,6,1,4,1,9,16]).

-define(ciscoPolicy, [1,3,6,1,4,1,9,17]).

-define(ciscoPIB, [1,3,6,1,4,1,9,17,2]).

-define(ciscoPolicyAuto, [1,3,6,1,4,1,9,18]).

-define(ciscoPibToMib, [1,3,6,1,4,1,9,18,2]).

-define(ciscoDomains, [1,3,6,1,4,1,9,19]).

-define(ciscoTDomains, [1,3,6,1,4,1,9,19,99999]).

-define(ciscoTDomainUdpIpv4, [1,3,6,1,4,1,9,19,99999,1]).

-define(ciscoTDomainUdpIpv6, [1,3,6,1,4,1,9,19,99999,2]).

-define(ciscoTDomainTcpIpv4, [1,3,6,1,4,1,9,19,99999,3]).

-define(ciscoTDomainTcpIpv6, [1,3,6,1,4,1,9,19,99999,4]).

-define(ciscoTDomainLocal, [1,3,6,1,4,1,9,19,99999,5]).

-define(ciscoTDomainClns, [1,3,6,1,4,1,9,19,99999,6]).

-define(ciscoTDomainCons, [1,3,6,1,4,1,9,19,99999,7]).

-define(ciscoTDomainDdp, [1,3,6,1,4,1,9,19,99999,8]).

-define(ciscoTDomainIpx, [1,3,6,1,4,1,9,19,99999,9]).

-define(ciscoTDomainSctpIpv4, [1,3,6,1,4,1,9,19,99999,10]).

-define(ciscoTDomainSctpIpv6, [1,3,6,1,4,1,9,19,99999,11]).

-define(ciscoCIB, [1,3,6,1,4,1,9,20]).

-define(ciscoCibMmiGroup, [1,3,6,1,4,1,9,20,1]).

-define(ciscoCibProvGroup, [1,3,6,1,4,1,9,20,2]).

-define(ciscoPKI, [1,3,6,1,4,1,9,21]).

-define(ciscoLDAP, [1,3,6,1,4,1,9,22]).


%% Range values


%% Default values

-endif.
