%%% This file was automatically generated by snmpc_mib_to_hrl
-ifndef('ESO-CONSORTIUM-MIB').
-define('ESO-CONSORTIUM-MIB', true).

%% Oids

-define(esoConsortiumMIB, [1,3,6,1,4,1,14832]).

-define(esoConsortiumMIBObjectIdentities, [1,3,6,1,4,1,14832,1]).

-define(usm3DESPrivProtocol, [1,3,6,1,4,1,14832,1,1]).

-define(usmAESCfb128PrivProtocol, [1,3,6,1,4,1,14832,1,2]).

-define(usmAESCfb192PrivProtocol, [1,3,6,1,4,1,14832,1,3]).

-define(usmAESCfb256PrivProtocol, [1,3,6,1,4,1,14832,1,4]).


%% Range values


%% Default values

-endif.
