/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-cisco-nso-nc-6.0.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.cisconso.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-cisco-nso-nc-6.0.yang */
public class tailfNedIdCiscoNsoNc6_0 extends ConfNamespace {
    public static final int hash = 148977973;
    public int hash() {
        return tailfNedIdCiscoNsoNc6_0.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/cisco-nso-nc-6.0";
    public String id() {
        return tailfNedIdCiscoNsoNc6_0.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/cisco-nso-nc-6.0";
    public String uri() {
        return tailfNedIdCiscoNsoNc6_0.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdCiscoNsoNc6_0.uri);
    }

    public static final String prefix = "cisco-nso-nc-6.0";
    public String prefix() {
        return tailfNedIdCiscoNsoNc6_0.prefix;
    }

    public tailfNedIdCiscoNsoNc6_0() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_nso_nc_60x2e0 = 1431833348;
    public static final String _cisco_nso_nc_60x2e0_ = "cisco-nso-nc-6.0";
}
